channels:
  - conda-forge
  - bioconda
dependencies:
  # Core scientific computing (from conda-forge)
  - python=3.10
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scipy
  - scikit-learn
  - h5py
  - tqdm

  # Jupyter (from conda-forge)
  - conda-forge::biopython
  - conda-forge::jupyter
  - conda-forge::jupyterlab
  - conda-forge::notebook
  - conda-forge::ipykernel
  - conda-forge::nbconvert
  - conda-forge::ipywidgets

  # Bioinformatics (explicitly from bioconda)
  - bioconda::samtools
  - bioconda::bcftools
  - bioconda::bedtools
  - bioconda::minimap2
  - bioconda::seqkit
  - bioconda::flye
  - bioconda::fastani
  # - bioconda::prokka # This is not working (solving package never finishes)
  - bioconda::fastp
  - bioconda::bamtools

  # Nanopore tools (explicitly from bioconda)
  - bioconda::nanofilt
  - bioconda::nanoplot
  - bioconda::rasusa
  - bioconda::porechop_abi